Support plugging in instrumentation based on ActivitySources
serilog-tracing/serilog-tracing pull request #153
Opened 2024-11-08 07:27 UTC by KodrAus

Closes #138 

This PR introduces a bridge between `DiagnosticSource`s and `ActivitySource`s so that libraries only using `ActivitySource`s for their instrumentation can still be enriched through SerilogTracing's `Instrument.With` infrastructure.

You can instrument an activity-source by inheriting from `ActivitySourceInstrumentor`:

```csharp
using SerilogTracing.Instrumentation;

using var _ = new ActivityListenerConfiguration()
    .Instrument.With<RabbitMQActivitySourceInstrumentor>()
    .TraceToSharedLogger();

class RabbitMQActivitySourceInstrumentor : ActivitySourceInstrumentor
{
    protected override bool ShouldSubscribeTo(string activitySourceName)
    {
        return activitySourceName.StartsWith("RabbitMQ");
    }

    protected override void InstrumentActivity(Activity activity)
    {
        ActivityInstrumentation.SetMessageTemplateOverride(..);
    }
}
```

2024-11-08 07:27 UTC, KodrAus commented on src/SerilogTracing/Instrumentation/ActivitySourceInstrumentor.cs
> +    protected abstract bool ShouldSubscribeTo(string activitySourceName);
Should these be `public`?

2024-11-08 09:39 UTC, KodrAus commented on src/SerilogTracing/Instrumentation/ActivitySourceInstrumentor.cs
> +    protected abstract bool ShouldSubscribeTo(string activitySourceName);
Opted for public, since that's what you get inheriting from `IActivityInstrumentor`.

2024-11-08 10:18 UTC, KodrAus commented
cc @ngbrown: I spent a lot of time tinkering with RabbitMQ's new activity instrumentation and arrived at this as a solution for enriching activities from "modern" sources that are based off `ActivitySource` instead of `DiagnosticSource`. Does this look like it would fit your needs?

2024-11-08 21:58 UTC, KodrAus commented
@ngbrown Ah in order to use `IActivitySourceInstrumentor`s you need to plug them in to your SerilogTracing configuration using `.Instrument.With`.

2024-11-08 22:14 UTC, KodrAus commented
Ah, no, I see. I’m simply passing the wrong value to subscribe to 🙂 My bad!

2024-11-08 22:19 UTC, ngbrown commented
> Ah, no, I see. I’m simply passing the wrong value to subscribe to 🙂 My bad!

Right, so to be clear, `public override void InstrumentActivity(Activity activity)` is going to get all events from all `ActivityListener` sources since `public override bool ShouldSubscribeTo(string activitySourceName)` doesn't get called? Is this expected?

It seems that there is no reason for `public abstract void InstrumentActivity(System.Diagnostics.Activity activity);` to exist unless it starts being called.

2024-11-08 23:22 UTC, ngbrown commented
> Ah, no, I see. I’m simply passing the wrong value to subscribe to 🙂 My bad!

This is working slightly better, but because it is hard-coded to "ActivityStarted" the tags with data are not yet populated. Those are populate after the `ActivityStarted` event has fired.

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/7c78e66a42fe13d81cf04b76975f86b13ecba23c/projects/RabbitMQ.Client/Impl/RabbitMQActivitySource.cs#L67-L77

The `ActivitySourceInstrumentor` base class would be better off with two separate virtual functions instead of a single abstract function. One for "ActivityStarted" and one for "ActivityStopped".

I can work around this with my own implementation of `IActivityInstrumentor`. I have to use string constants because the relevant constants in `SerilogTracing.Core.Constants` are all internal.

<details>
<summary>RabbitMQClientActivityInstrumentor.cs with IActivityInstrumentor instead of ActivitySourceInstrumentor</summary>

```cs
using System.Diagnostics;
using Serilog.Events;
using Serilog.Parsing;

namespace SerilogTracing.Instrumentation.RabbitMQ;

/// <summary>
/// An activity instrumentor that populates the current activity a template for the RabbitMQ client
/// </summary>
internal sealed class RabbitMQClientActivityInstrumentor : IActivityInstrumentor
{
    /// <summary>
    /// Create an instance of the instrumentor.
    /// </summary>
    public RabbitMQClientActivityInstrumentor(RabbitMQClientActivityInstrumentationOptions options)
    {
        _getSubscriberProperties = options.GetSubscriberProperties;
        _getPublisherProperties = options.GetPublisherProperties;

        var messageTemplateParser = new MessageTemplateParser();
        _subscriberMessageTemplateOverride = messageTemplateParser.Parse(options.SubscriberMessageTemplate);
        _publisherMessageTemplateOverride = messageTemplateParser.Parse(options.PublisherMessageTemplate);
    }

    private readonly Func<Activity, IEnumerable<LogEventProperty>> _getSubscriberProperties;
    private readonly Func<Activity, IEnumerable<LogEventProperty>> _getPublisherProperties;
    private readonly MessageTemplate _subscriberMessageTemplateOverride;
    private readonly MessageTemplate _publisherMessageTemplateOverride;

    bool IActivityInstrumentor.ShouldSubscribeTo(string diagnosticListenerName)
    {
        return diagnosticListenerName == "SerilogTracing.ActivitySource";
    }

    public bool ShouldSubscribeTo(string activitySourceName)
    {
        return activitySourceName.StartsWith("RabbitMQ.Client", StringComparison.OrdinalIgnoreCase);
    }

    public void InstrumentActivity(Activity activity, string eventName, object eventArgs)
    {
        if (eventName != "ActivityStopped" || !ShouldSubscribeTo(activity.Source.Name)) return;

        SerilogTracing.Core.Constants

        switch (activity.Source.Name)
        {
            case "RabbitMQ.Client.Subscriber":
                ActivityInstrumentation.SetMessageTemplateOverride(activity, _subscriberMessageTemplateOverride);
                ActivityInstrumentation.SetLogEventProperties(activity, _getSubscriberProperties(activity));
                break;
            case "RabbitMQ.Client.Publisher":
                ActivityInstrumentation.SetMessageTemplateOverride(activity, _publisherMessageTemplateOverride);
                ActivityInstrumentation.SetLogEventProperties(activity, _getPublisherProperties(activity));
                break;
            default:
                throw new NotImplementedException($"No template for the activity source {activity.Source.Name}");
        }
    }
}
```

</details>

2024-11-08 23:32 UTC, ngbrown requested changes
Because setting the message template only at activity start isn't desirable in some cases (like with RabbitMQ), there should be the ability to also instrument the activity when the activity has stopped.

2024-11-08 23:32 UTC, ngbrown commented on src/SerilogTracing/Instrumentation/ActivitySourceInstrumentor.cs
> +    public abstract void InstrumentActivity(Activity activity);
Make this a virtual function with an empty default implementation and re-name it to `InstrumentOnActivityStarted`.

2024-11-08 23:32 UTC, ngbrown commented on src/SerilogTracing/Instrumentation/ActivitySourceInstrumentor.cs
> +        }
Add the second case for `Constants.SerilogTracingActivityStoppedEventName` and call a virtual function with an empty default implementation called `InstrumentOnActivityStopped`.

2024-11-09 00:12 UTC, KodrAus commented
Thanks for the feedback @ngbrown 🙇 Those are great suggestions.

2024-11-09 00:13 UTC, KodrAus commented
For what it’s worth, I wouldn’t be against making those constants for the diagnostic listener name and events public either, since they indirectly are already via the diagnostic listener discovery mechanism.

2024-11-09 04:41 UTC, ngbrown approved these changes
Looks good.

The RabbitMQ.Client library is only populating `Activity.Links` and not `Activity.Parent` so it doesn't give a complete trace view in Seq, but I don't think there is anything you can do about that in this library. See https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1666#issuecomment-2466041710 for my comment on that.

2024-11-09 05:00 UTC, KodrAus commented
Thanks @ngbrown. I ran into this as well while I was tinkering with it and was tossing up whether to log an issue for it. Glad to see one already exists.

I think we do need to do something in Seq to support span links, but that's a separate issue. They generalize traces from being trees into any (hopefully acyclic) graph, so the waterfall visualization isn't necessarily the best for them.

Ideally, it should be configurable in RabbitMQ, which it looks like they're open to, since converting links into a parent/child basically isn't possible with the activity parent being frozen once it's started.

As for SerilogTracing, we had also thought about letting you set an override parent context to an activity in these cases where you're stuck. It won't change what's on the activity, but will be used when converting the activity into a log event. It could look something like:

```csharp
ActivityInstrumentation.SetParentContextOverride(new SpanContext(traceId, parentSpanId, traceFlags));
```

2024-11-10 02:30 UTC, nblumhardt approved these changes
Looks good to me!

I'm warming to the `SetParentContextOverride()` idea the more that I think about it - nice to be able to put those things in the hands of the consumer :) 👍

2024-11-10 02:30 UTC, nblumhardt commented on src/SerilogTracing/Instrumentation/ActivitySourceInstrumentor.cs
> +    }
Nit: bit of extra whitespace here; it'd be fine for the empty braces to follow the argument list i.e. `...) { }`

2024-11-10 21:36 UTC, merged